// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDECwS1GVS0qFZdNeMYkTw0ompNZSZR0Js',
    appId: '1:362191676384:web:01c0536aa335a4e08f0185',
    messagingSenderId: '362191676384',
    projectId: 'nepraproject',
    authDomain: 'nepraproject.firebaseapp.com',
    storageBucket: 'nepraproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkyi2cfvPvyTuiPQ31luOblMnJpgDd5cY',
    appId: '1:362191676384:android:d84b050f8b9a59648f0185',
    messagingSenderId: '362191676384',
    projectId: 'nepraproject',
    storageBucket: 'nepraproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLIcg52im_ReANHBaF0M1sia2QEuO-ptU',
    appId: '1:362191676384:ios:4d4547e4f8c3e1238f0185',
    messagingSenderId: '362191676384',
    projectId: 'nepraproject',
    storageBucket: 'nepraproject.appspot.com',
    iosBundleId: 'com.example.nepraproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLIcg52im_ReANHBaF0M1sia2QEuO-ptU',
    appId: '1:362191676384:ios:6cac1a47700babe68f0185',
    messagingSenderId: '362191676384',
    projectId: 'nepraproject',
    storageBucket: 'nepraproject.appspot.com',
    iosBundleId: 'com.example.nepraproj.RunnerTests',
  );
}
